# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x17\n\x07TextReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x17\n\x07TextRep\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"+\n\x0cSplitTextReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x02 \x01(\t\",\n\x0cSplitTextRep\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\r\n\x05\x63hunk\x18\x02 \x03(\t\"\x1b\n\tNumberReq\x12\x0e\n\x06number\x18\x01 \x01(\r\"\x1b\n\tNumberRep\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\x8b\x01\n\x0eUnicornService\x12#\n\x0bReverseText\x12\x08.TextReq\x1a\x08.TextRep\"\x00\x12+\n\tSplitText\x12\r.SplitTextReq\x1a\r.SplitTextRep\"\x00\x12\'\n\x07IsPrime\x12\n.NumberReq\x1a\n.NumberRep\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTREQ._serialized_start=17
  _TEXTREQ._serialized_end=40
  _TEXTREP._serialized_start=42
  _TEXTREP._serialized_end=65
  _SPLITTEXTREQ._serialized_start=67
  _SPLITTEXTREQ._serialized_end=110
  _SPLITTEXTREP._serialized_start=112
  _SPLITTEXTREP._serialized_end=156
  _NUMBERREQ._serialized_start=158
  _NUMBERREQ._serialized_end=185
  _NUMBERREP._serialized_start=187
  _NUMBERREP._serialized_end=214
  _UNICORNSERVICE._serialized_start=217
  _UNICORNSERVICE._serialized_end=356
# @@protoc_insertion_point(module_scope)
