# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\nPutRequest\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x1d\n\x0bPutResponse\x12\x0e\n\x06is_put\x18\x01 \x01(\x08\"\x1c\n\x0cPeekResponse\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x1b\n\x0bPopResponse\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x1c\n\x0cSizeResponse\x12\x0c\n\x04size\x18\x01 \x01(\r2\xbb\x01\n\x0cQueueService\x12 \n\x03put\x12\x0b.PutRequest\x1a\x0c.PutResponse\x12-\n\x04peek\x12\x16.google.protobuf.Empty\x1a\r.PeekResponse\x12+\n\x03pop\x12\x16.google.protobuf.Empty\x1a\x0c.PopResponse\x12-\n\x04size\x12\x16.google.protobuf.Empty\x1a\r.SizeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUTREQUEST._serialized_start=44
  _PUTREQUEST._serialized_end=70
  _PUTRESPONSE._serialized_start=72
  _PUTRESPONSE._serialized_end=101
  _PEEKRESPONSE._serialized_start=103
  _PEEKRESPONSE._serialized_end=131
  _POPRESPONSE._serialized_start=133
  _POPRESPONSE._serialized_end=160
  _SIZERESPONSE._serialized_start=162
  _SIZERESPONSE._serialized_end=190
  _QUEUESERVICE._serialized_start=193
  _QUEUESERVICE._serialized_end=380
# @@protoc_insertion_point(module_scope)
